package com.calculator.scientific.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val LightPrimary = Color(0xFF1565C0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF546E7A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3EB)
val LightOnSecondaryContainer = Color(0xFF0E1D24)
val LightTertiary = Color(0xFF6D5E00)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFBE365)
val LightOnTertiaryContainer = Color(0xFF221B00)
val LightBackground = Color(0xFFF8F9FF)
val LightOnBackground = Color(0xFF191C20)
val LightSurface = Color(0xFFF8F9FF)
val LightOnSurface = Color(0xFF191C20)
val LightSurfaceVariant = Color(0xFFDFE2EB)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// Dark theme colors
val DarkPrimary = Color(0xFF9ECAFF)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF00497D)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBBC8D0)
val DarkOnSecondary = Color(0xFF253239)
val DarkSecondaryContainer = Color(0xFF3C4950)
val DarkOnSecondaryContainer = Color(0xFFD7E3EB)
val DarkTertiary = Color(0xFFDEC74C)
val DarkOnTertiary = Color(0xFF3A3000)
val DarkTertiaryContainer = Color(0xFF534600)
val DarkOnTertiaryContainer = Color(0xFFFBE365)
val DarkBackground = Color(0xFF111318)
val DarkOnBackground = Color(0xFFE1E2E8)
val DarkSurface = Color(0xFF111318)
val DarkOnSurface = Color(0xFFE1E2E8)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)

// Calculator-specific colors
val OperatorColor = Color(0xFF1565C0)
val OperatorColorDark = Color(0xFF9ECAFF)
val NumberColor = Color(0xFF37474F)
val NumberColorDark = Color(0xFFE0E0E0)
val FunctionColor = Color(0xFF6D5E00)
val FunctionColorDark = Color(0xFFDEC74C)
val EqualsColor = Color(0xFF1565C0)
val EqualsColorDark = Color(0xFF9ECAFF)
val ClearColor = Color(0xFFC62828)
val ClearColorDark = Color(0xFFFFB4AB)
